Making sure the openssl098e-package is installed on rhel distros.
Trying to make sure we got necessary libraries before continuing the
build process on rhel systems.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -171,10 +171,13 @@ case "$dist" in
 			dist='Ubuntu'
         fi
         ;;
-    CentOS|RedHatEnterpriseServer)
+    CentOS|RedHatEnterpriseServer|RedHatEnterpriseWorkstation)
         echo -n "($dist handled as RHEL)..."
         dist='RHEL'
         ;;
+    *)  
+        echo -n "(no \"special configuration\" of distro needed)..."
+        ;; 
 esac
 echo $dist
 
@@ -203,6 +206,32 @@ else
     archlib='^[ ]*/lib/|/usr/lib/'
 fi
 echo $arch
+
+# Check for openlssl-compatibility package on distros determined as RHEL, 
+if [ $dist == "RHEL" ]; then
+    # Just to be sure we got what we need, 
+    echo -n "Locating rpm-binary:... "
+    if command -v rpm &> /dev/null ; then 
+        sts=$(rpm --version)
+        echo "$sts (ok)"
+    else
+        echo -n >&2 "Cannot find rpm-binary. Your installation is seriously "
+        echo    >&2 "broken. Giving up."
+        exit 2;  
+    fi
+
+    # Try to query the needed rpm, 
+    echo -n "Checking for openssl098e-compatibility libraries..."
+    if [[ -f $(rpm --eval %_libdir/libssl.so.0.9.8e) && 
+          -f $(rpm --eval %_libdir/libcrypto.so.0.9.8e) ]] ; then 
+        echo "found (ok)"
+    else 
+        echo >&2 "Could not find necessary openssl098e-compatibility libraries."
+        echo -n >&2 "Suggestion: Try to install package with 'sudo yum install "
+        echo >&2 "-y openssl098e'." 
+        exit 2
+    fi
+fi
 
 if [ -z "$package" ]; then
     echo -n "Determine .deb file..."
